version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: floodwatch-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      SPRING_DATASOURCE_USERNAME: RM556182
      SPRING_DATASOURCE_PASSWORD: 101003
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - floodwatch-net
    restart: unless-stopped

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: floodwatch-oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: MinhaSenhaSuperSeguraOracle123
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/MinhaSenhaSuperSeguraOracle123@localhost:1521/XEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 80s
    networks:
      - floodwatch-net
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local

networks:
  floodwatch-net:
    driver: bridge
